# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceStub(object):
    """Inference service provides LLM completion capabilities.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Completion = channel.unary_unary(
                '/navigator.inference.v1.Inference/Completion',
                request_serializer=inference__pb2.CompletionRequest.SerializeToString,
                response_deserializer=inference__pb2.CompletionResponse.FromString,
                _registered_method=True)
        self.CreateInferenceRoute = channel.unary_unary(
                '/navigator.inference.v1.Inference/CreateInferenceRoute',
                request_serializer=inference__pb2.CreateInferenceRouteRequest.SerializeToString,
                response_deserializer=inference__pb2.InferenceRouteResponse.FromString,
                _registered_method=True)
        self.UpdateInferenceRoute = channel.unary_unary(
                '/navigator.inference.v1.Inference/UpdateInferenceRoute',
                request_serializer=inference__pb2.UpdateInferenceRouteRequest.SerializeToString,
                response_deserializer=inference__pb2.InferenceRouteResponse.FromString,
                _registered_method=True)
        self.DeleteInferenceRoute = channel.unary_unary(
                '/navigator.inference.v1.Inference/DeleteInferenceRoute',
                request_serializer=inference__pb2.DeleteInferenceRouteRequest.SerializeToString,
                response_deserializer=inference__pb2.DeleteInferenceRouteResponse.FromString,
                _registered_method=True)
        self.ListInferenceRoutes = channel.unary_unary(
                '/navigator.inference.v1.Inference/ListInferenceRoutes',
                request_serializer=inference__pb2.ListInferenceRoutesRequest.SerializeToString,
                response_deserializer=inference__pb2.ListInferenceRoutesResponse.FromString,
                _registered_method=True)


class InferenceServicer(object):
    """Inference service provides LLM completion capabilities.
    """

    def Completion(self, request, context):
        """Send a completion request routed by the server's inference router.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInferenceRoute(self, request, context):
        """Create a new inference route.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInferenceRoute(self, request, context):
        """Update an existing inference route.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInferenceRoute(self, request, context):
        """Delete an inference route.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInferenceRoutes(self, request, context):
        """List inference routes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Completion': grpc.unary_unary_rpc_method_handler(
                    servicer.Completion,
                    request_deserializer=inference__pb2.CompletionRequest.FromString,
                    response_serializer=inference__pb2.CompletionResponse.SerializeToString,
            ),
            'CreateInferenceRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInferenceRoute,
                    request_deserializer=inference__pb2.CreateInferenceRouteRequest.FromString,
                    response_serializer=inference__pb2.InferenceRouteResponse.SerializeToString,
            ),
            'UpdateInferenceRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInferenceRoute,
                    request_deserializer=inference__pb2.UpdateInferenceRouteRequest.FromString,
                    response_serializer=inference__pb2.InferenceRouteResponse.SerializeToString,
            ),
            'DeleteInferenceRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInferenceRoute,
                    request_deserializer=inference__pb2.DeleteInferenceRouteRequest.FromString,
                    response_serializer=inference__pb2.DeleteInferenceRouteResponse.SerializeToString,
            ),
            'ListInferenceRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInferenceRoutes,
                    request_deserializer=inference__pb2.ListInferenceRoutesRequest.FromString,
                    response_serializer=inference__pb2.ListInferenceRoutesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'navigator.inference.v1.Inference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('navigator.inference.v1.Inference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inference(object):
    """Inference service provides LLM completion capabilities.
    """

    @staticmethod
    def Completion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.inference.v1.Inference/Completion',
            inference__pb2.CompletionRequest.SerializeToString,
            inference__pb2.CompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInferenceRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.inference.v1.Inference/CreateInferenceRoute',
            inference__pb2.CreateInferenceRouteRequest.SerializeToString,
            inference__pb2.InferenceRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInferenceRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.inference.v1.Inference/UpdateInferenceRoute',
            inference__pb2.UpdateInferenceRouteRequest.SerializeToString,
            inference__pb2.InferenceRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteInferenceRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.inference.v1.Inference/DeleteInferenceRoute',
            inference__pb2.DeleteInferenceRouteRequest.SerializeToString,
            inference__pb2.DeleteInferenceRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInferenceRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.inference.v1.Inference/ListInferenceRoutes',
            inference__pb2.ListInferenceRoutesRequest.SerializeToString,
            inference__pb2.ListInferenceRoutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
